# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: npmjs-sample-variables
- name: sonarQubeTags
  value: pipelines
- name: sonarQubeKey
  value: pipelines-teste
- name: sonarQubeName
  value: 'Pipelines Teste'
- name: framework
  value: javascript

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: feature/add-sonarAllBranchs

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: npmjs-sample
    type: javascript
    to: semantic-release
    skipSonarBranch: false
    npmCmds:
    - npm install
