# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: 4f149cb0-a52e-4ad4-be49-c6952fb5aa74

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/heads/feature/npm-semantic-release

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: npmjs-sample
    type: javascript
    to: semantic-release
    npmCmds:
    - 'npm install'
    - 'npm run test'
    - 'npm run build'
